# Generated by Django 3.2.23 on 2024-04-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('percent', models.PositiveIntegerField(default=0, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_time', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('phone_number', models.CharField(max_length=19)),
                ('address_line1', models.CharField(default='', max_length=200)),
                ('address_line2', models.CharField(default='', max_length=200)),
                ('region', models.CharField(max_length=85)),
                ('city', models.CharField(max_length=85)),
                ('postcode', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(max_length=56)),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('order_status', models.CharField(max_length=40)),
                ('order_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='checkout.discount')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_total', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('product_quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
