# Generated by Django 3.2.23 on 2024-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
