# Generated by Django 3.2.23 on 2024-04-20 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240420_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='code',
            new_name='discount_code',
        ),
    ]
