# Generated by Django 3.2.23 on 2024-04-07 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_order_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='order_line',
            new_name='order',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='order_subtotal',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='order_total',
        ),
        migrations.RemoveField(
            model_name='orderlineitem',
            name='shipping_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='checkout.discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
