# Generated by Django 3.2.23 on 2024-07-02 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_discount_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message="Phone number must be entered in the format: '+123456789'.                     Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Only letters, numbers and hyphens allowed.', regex='^[\\d\\-a-zA-Z]+$')]),
        ),
    ]
