# Generated by Django 3.2.23 on 2024-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20240407_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_line2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
