# Generated by Django 3.2.23 on 2024-04-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_rename_code_discount_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Awaiting Fulfillment', 'Awaiting Fulfillment'), ('Awaiting Shipment', 'Awaiting Shipment'), ('Order Shipped', 'Order Shipped'), ('Order Completed', 'Order Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Partially Refunded', 'Partially Refunded'), ('Disputed', 'Disputed')], default='Awaiting Fulfillment', max_length=40),
        ),
    ]
