# Generated by Django 3.2.23 on 2024-07-04 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='checkout.discount'),
        ),
    ]
