# Generated by Django 3.2.23 on 2024-07-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
