# Generated by Django 3.2.23 on 2024-04-21 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_full_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('saved_email', models.EmailField(blank=True, max_length=300, null=True)),
                ('saved_phone_number', models.CharField(blank=True, max_length=19, null=True)),
                ('saved_address_line1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('saved_address_line2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('saved_region', models.CharField(blank=True, max_length=85, null=True)),
                ('saved_city', models.CharField(blank=True, max_length=85, null=True)),
                ('saved_postcode', models.CharField(blank=True, max_length=30, null=True)),
                ('saved_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
