# Generated by Django 3.2.23 on 2024-07-01 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_saved_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='saved_postcode',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Only letters, numbers and hyphens allowed.', regex='^[\\d\\-a-zA-Z]+$')]),
        ),
    ]
