# Generated by Django 3.2.23 on 2024-04-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('condition', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('primary_colour', models.CharField(choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('PURPLE', 'PURPLE'), ('PINK', 'PINK'), ('ORANGE', 'ORANGE'), ('BROWN', 'BROWN'), ('GREY', 'GREY'), ('GOLD', 'GOLD'), ('COPPER', 'COPPER'), ('SILVER', 'SILVER'), ('MULTICOLOUR', 'MULTICOLOUR')], default='BLACK', max_length=50)),
                ('secondary_colour', models.CharField(choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('PURPLE', 'PURPLE'), ('PINK', 'PINK'), ('ORANGE', 'ORANGE'), ('BROWN', 'BROWN'), ('GREY', 'GREY'), ('GOLD', 'GOLD'), ('COPPER', 'COPPER'), ('SILVER', 'SILVER'), ('MULTICOLOUR', 'MULTICOLOUR')], default='BLACK', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
