# Generated by Django 3.2.23 on 2024-04-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('unknown category', 'unknown category'), ('tops', 'tops'), ('trousers', 'trousers'), ('skirts', 'skirts'), ('dresses', 'dresses'), ('footwear', 'footwear'), ('outerwear', 'outerwear')], default='unknown category', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.category'),
        ),
    ]
