# Generated by Django 3.2.23 on 2024-02-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20240206_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
