# Generated by Django 3.2.23 on 2024-07-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('IN STOCK', 'IN STOCK'), ('SOLD OUT', 'SOLD OUT')], default='IN STOCK', max_length=20),
        ),
    ]
