# Generated by Django 3.2.23 on 2024-02-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='friendly_name',
        ),
        migrations.AddField(
            model_name='product',
            name='colours',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('PURPLE', 'PURPLE'), ('PINK', 'PINK'), ('ORANGE', 'ORANGE'), ('BROWN', 'BROWN'), ('GREY', 'GREY'), ('GOLD', 'GOLD'), ('COPPER', 'COPPER'), ('SILVER', 'SILVER'), ('MULTICOLOUR', 'MULTICOLOUR')], default='BLACK', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
