# Generated by Django 3.2.23 on 2024-02-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240211_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colours',
            new_name='primary_colour',
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_colour',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('YELLOW', 'YELLOW'), ('GREEN', 'GREEN'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('PURPLE', 'PURPLE'), ('PINK', 'PINK'), ('ORANGE', 'ORANGE'), ('BROWN', 'BROWN'), ('GREY', 'GREY'), ('GOLD', 'GOLD'), ('COPPER', 'COPPER'), ('SILVER', 'SILVER'), ('MULTICOLOUR', 'MULTICOLOUR')], default='BLACK', max_length=50),
        ),
    ]
