# Generated by Django 3.2.23 on 2024-04-07 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_sold_out',
        ),
    ]
